# frozen_string_literal: true

# Phase 3 — remove the provisioning exemption entirely.
#
# BACKGROUND (docs/security/findings.md SEC-003)
#
# The original design gave `organizations` a second, named policy so that a row
# could be inserted before its own tenant context existed:
#
#   CREATE POLICY organizations_provisioning ON organizations
#     FOR INSERT WITH CHECK (current_setting('nexus.provisioning', true) = 'on');
#
# It did not work, and the way it failed is worth recording. A bare INSERT was
# accepted, but `INSERT ... RETURNING id` — which ActiveRecord *always* emits —
# was rejected with the same message:
#
#   ERROR:  new row violates row-level security policy for table "organizations"
#
# The message points at WITH CHECK, but the actual cause is RETURNING: it must
# read the row back, and reading is governed by the USING clause. A `FOR INSERT`
# policy has no USING clause, and the tenant policy's USING evaluated to NULL
# because no tenant was set. So the write was permitted and the read-back was
# not.
#
# THE FIX
#
# Rather than adding a matching SELECT exemption — which would have made every
# organization readable for the duration of a provisioning transaction — the
# organization's UUID is now generated by the application, the tenant context is
# set to it *before* the INSERT, and provisioning becomes an ordinary
# tenant-scoped write that the existing policy already permits.
#
# Net effect: one policy instead of two, no exemption, no session flag, and no
# window in which the tenant policy is not the only rule. The special case is
# gone rather than fixed.
class RemoveProvisioningPolicyExemption < ActiveRecord::Migration[7.1]
  def up
    execute "DROP POLICY IF EXISTS organizations_provisioning ON organizations;"
  end

  def down
    execute <<~SQL
      CREATE POLICY organizations_provisioning ON organizations
        FOR INSERT
        WITH CHECK (current_setting('nexus.provisioning', true) = 'on');
    SQL
  end
end
